services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tickets
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: helpdesk-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/tickets?schema=public
      - JWT_SECRET=your_jwt_secret_here
      - JWT_EXPIRES_IN=3600s
      - STRIPE_SECRET_KEY=sk_test_xxx
      - STRIPE_WEBHOOK_SECRET=whsec_xxx
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

volumes:
  postgres_data: